/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Home from "./scene/Home"
import HUD from "./scene/HUD"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="showall";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="HUD.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scene/Home.ts",Home);
        reg("scene/HUD.ts",HUD);
    }
}
GameConfig.init();